@baseUrl=https://www.bisno.ao/api


### Create bisno
POST {{baseUrl}}/bisnos/create
Content-Type: application/json
Accept: application/json

{
  "customerName": "Délcio Capolo",
  "customerMobile": "+244923456789",
  "customerMobileHasWhatsapp": true,
  "serviceId": "0a5c613c-aae6-42d0-bc70-41d5d3379d3b",
  "zoneId": "d22b8d5c-7d12-44b3-b2b3-b7410acd3ec2",
  "description": "Preciso trocar o visor do meu iPhone 12 Normal"
}

### List Mixeiros
GET {{baseUrl}}/mixeiros
Accept: application/json

### Create Mixeiro
POST {{baseUrl}}/mixeiros/create
Content-Type: application/json
Accept: application/json

{
  "categoryId": "fca88cdd-052d-47c3-8893-a51038fa0987",
  "zoneId": "c7c39fdc-1247-416b-a245-2802147e2a0f",
  "customName": "Délcio Capolo",
  "bi": "010278995LA047",
  "email": "delciocapolo096@gmail.com",
  "password": "testando",
  "channel": "whatsapp",
  "mobile": "+244935785831",
  "hasWhatsapp": true
}

### Create Mixeiro Subscription
POST {{baseUrl}}/mixeiro-subscriptions/create
Content-Type: application/json
Accept: application/json

{
  "planId": "9ac3c959-02bd-4247-9ece-581fec3e939b",
  "mixeiroId": "f376a077-300b-4100-857d-7570c01e91eb"
}
