@baseUrl=https://www.bisno.ao/api


### Create bisno
POST {{baseUrl}}/bisnos/create
Content-Type: application/json
Accept: application/json

{
  "customerName": "João Sebastião",
  "customerMobile": "+244959006410",
  "customerMobileHasWhatsapp": true,
  "serviceId": "15324893-1018-45e4-afa5-17dd6b186353",
  "zoneId": "8b172494-0373-4c44-8721-d6c8201fa071",
  "description": "Preciso trocar o visor do meu iPhone 12 Normal"
}

### List Mixeiros
GET {{baseUrl}}/mixeiros
Accept: application/json

### Create Mixeiro
POST {{baseUrl}}/mixeiros/create
Content-Type: application/json
Accept: application/json

{
  "categoryId": "9a901491-2e51-4655-8f3d-0ce92fd408c1",
  "zoneId": "8b172494-0373-4c44-8721-d6c8201fa071",
  "customName": "Délcio Capolo",
  "bi": "010278995LA047",
  "email": "delciocapolo096@gmail.com",
  "password": "testando",
  "channel": "whatsapp",
  "mobile": "+244935785831",
  "hasWhatsapp": true
}

### Create Mixeiro Subscription
POST {{baseUrl}}/mixeiro-subscriptions/create
Content-Type: application/json
Accept: application/json

{
  "planId": "9ac3c959-02bd-4247-9ece-581fec3e939b",
  "mixeiroId": "f376a077-300b-4100-857d-7570c01e91eb"
}
