services:
  app:
    build:
      context: ../backend
      target: dev_dependencies
    entrypoint: []
    command: ["pnpm", "run", "dev"]
    volumes:
      - ../backend/src:/usr/src/app/src
      - ../backend/package.json:/usr/src/app/package.json
      - ../backend/tsconfig.json:/usr/src/app/tsconfig.json
      - ../backend/.sequelizerc:/usr/src/app/.sequelizerc

  nginx:
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./certs:/etc/letsencrypt:ro

  evolution-api:
    ports:
      - "8080:8080"

  db:
    ports:
      - "5432:5432"
